In [1]:
import numpy as np

In [3]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [5]:
arr.shape = (2, 4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [6]:
arr = np.arange(8)
arr_new = arr.reshape((2, 4))
arr_new

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [7]:
arr = np.arange(8)
arr_new = arr.reshape((2, 4), order='F')
arr_new

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [8]:
arr = np.arange(8)
arr.shape = (2, 4)
arr
# array([[0, 1, 2, 3],
#        [4, 5, 6, 7]])

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [9]:
arr_trans = arr.transpose()
arr_trans
# array([[0, 4],
#        [1, 5],
#        [2, 6],
#        [3, 7]])

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [10]:
arr = np.arange(3)
print(arr.shape)
# (3,)
arr_trans = arr.transpose()
print(arr_trans.shape)
# (3,)

(3,)
(3,)


In [11]:
arr = np.linspace(1, 2, 6)
arr
# array([1. , 1.2, 1.4, 1.6, 1.8, 2. ])

array([1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [12]:
print(arr[2])
# 1.4

1.4


In [13]:
print(arr[2:4])
# [1.4 1.6]

[1.4 1.6]


In [14]:
print(arr[::-1])
# [2.  1.8 1.6 1.4 1.2 1. ]

[2.  1.8 1.6 1.4 1.2 1. ]


In [15]:
nd_array =  np.linspace(0, 6, 12, endpoint=False).reshape(3,4)
nd_array
# array([[0. , 0.5, 1. , 1.5],
#        [2. , 2.5, 3. , 3.5],
#        [4. , 4.5, 5. , 5.5]])

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [16]:
nd_array[1][2]
# 3.0

3.0

In [17]:
nd_array[1, 2]
# 3.0

3.0

In [18]:
nd_array[:2, 2]
# array([1., 3.])

array([1., 3.])

In [19]:
nd_array[1:, 2:4]
# array([[3. , 3.5],
#       [5. , 5.5]])

array([[3. , 3.5],
       [5. , 5.5]])

In [20]:
nd_array[:, 2:4]
# array([[1. , 1.5],
#       [3. , 3.5],
#       [5. , 5.5]])

array([[1. , 1.5],
       [3. , 3.5],
       [5. , 5.5]])

In [21]:
nd_array[:2]
# array([[0. , 0.5, 1. , 1.5],
#       [2. , 2.5, 3. , 3.5]])

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5]])

In [23]:
'В переменную elem_5_3 сохраните элемент из 5 строки и 3 столбца'

'В переменную last сохраните элемент из последней строки последнего столбца'

'В переменную line_4 сохраните строку 4'

'В переменную col_2 сохраните предпоследний столбец'

'Из строк 2-4 (включительно) получите столбцы 3-5 (включительно). Результат сохраните в переменную part'
'Сохраните в переменную rev последний столбец в обратном порядке'

'Сохраните в переменную trans транспонированный массив'


import numpy as np
mystery = np.array([[-13586,  15203,  28445, -27117,  -1781, -17182, -18049],
       [ 25936, -30968,  -1297,  -4593,   6451,  15790,   7181],
       [ 13348,  28049,  28655,  -6012,  21762,  25397,   8225],
       [ 13240,   7994,  32592,  20149,  13754,  11795,   -564],
       [-21725,  -8681,  30305,  22260, -17918,  12578,  29943],
       [-16841, -25392, -17278,  11740,   5916,    -47, -32037]],
      dtype=np.int16)
elem_5_3 = mystery[4,2]
print(elem_5_3)
last = mystery[5,6]
print(last)
line_4 = mystery[3,:]
print(line_4)
col_2 = mystery[:,5]
print(col_2)
part = mystery[1:4, 2:5]
print(part)
rev_1 = mystery[:,6]
rev = rev_1[::-1]
print(rev)
trans = mystery.transpose()
print(trans)

30305
-32037
[13240  7994 32592 20149 13754 11795  -564]
[-17182  15790  25397  11795  12578    -47]
[[-1297 -4593  6451]
 [28655 -6012 21762]
 [32592 20149 13754]]
[-32037  29943   -564   8225   7181 -18049]
[[-13586  25936  13348  13240 -21725 -16841]
 [ 15203 -30968  28049   7994  -8681 -25392]
 [ 28445  -1297  28655  32592  30305 -17278]
 [-27117  -4593  -6012  20149  22260  11740]
 [ -1781   6451  21762  13754 -17918   5916]
 [-17182  15790  25397  11795  12578    -47]
 [-18049   7181   8225   -564  29943 -32037]]


#sort

In [24]:
arr = np.array([23,12,45,12,23,4,15,3])
arr_new = np.sort(arr)
print(arr)
# [23 12 45 12 23  4 15  3]
print(arr_new)
# [ 3  4 12 12 15 23 23 45]

[23 12 45 12 23  4 15  3]
[ 3  4 12 12 15 23 23 45]


In [25]:
arr = np.array([23,12,45,12,23,4,15,3])
print(arr.sort())
# None
print(arr)
# [ 3  4 12 12 15 23 23 45]

None
[ 3  4 12 12 15 23 23 45]


In [26]:
data = np.array([4, 9, -4, 3])

In [27]:
roots = np.sqrt(data)
roots
# RuntimeWarning: invalid value encountered in sqrt
# array([2.        , 3.        ,        nan, 1.73205081])

C:\Users\CheshirSmile\AppData\Local\Temp\ipykernel_31632\2040053643.py:1: RuntimeWarning: invalid value encountered in sqrt
  roots = np.sqrt(data)


array([2.        , 3.        ,        nan, 1.73205081])

In [28]:
print(type(None))
# <class 'NoneType'>
print(type(np.nan))
# <class 'float'>
type(np.nan)

<class 'NoneType'>
<class 'float'>


float

In [29]:
print(None == None)
# True
print(np.nan == np.nan)
# False

True
False


In [30]:
print(None is None)
# True
print(np.nan is np.nan)
# True
print(np.nan is None)
# False

True
True
False


In [31]:
sum(roots)
# nan

nan

In [32]:
np.isnan(roots)
# array([False, False,  True, False])

array([False, False,  True, False])

In [33]:
roots[np.isnan(roots)]
# array([nan])

array([nan])

In [34]:
roots[np.isnan(roots)] = 0
roots
# array([2.        , 3.        , 0.        , 1.73205081])

array([2.        , 3.        , 0.        , 1.73205081])

In [35]:
sum(roots)
# 6.732050807568877

6.732050807568877

In [37]:
None == None

True

In [38]:
np.nan == np.nan

False

In [39]:
None is None

True

In [40]:
np.nan is np.nan

True

In [41]:
np.nan == None

False

In [42]:
np.isnan(np.nan)

True

Получите булевый массив nans_index с информацией о np.nan в массиве mystery: True - значение пропущено, False - значение не пропущено

В переменную `n_nan сохраните число пропущенных значений

Скопируйте массив mystery в массив mystery_new. Заполните пропущенные значения в массиве mystery_new нулями

Поменяйте тип данных в массиве mystery на int32 и сохраните в переменную mystery_int

Отсортируйте значения в массиве по возрастанию и сохраните результат в переменную array

Сохраните в массив table двухмерный массив, полученный из массива array. В нём должно быть 5 строк и 3 столбца. Причём порядок заполнения должен быть по столбцам!

In [44]:
import numpy as np

mystery = np.array([ 12279., -26024.,  28745.,  np.nan,  31244.,  -2365.,  -6974.,
        -9212., np.nan, -17722.,  16132.,  25933.,  np.nan, -16431.,
        29810.], dtype=np.float32)

nans_index = np.isnan(mystery)
print(nans_index)
n_nan = sum(np.isnan(mystery))
print(n_nan)
mystery_new = mystery
mystery_new[np.isnan(mystery_new)] = 0
print(mystery_new)
mystery_int = np.int32(mystery)
print(mystery_int)
array = np.sort(mystery)
print(array)
table = array.reshape((5, 3), order='F')
print(table)
col = table[:,1]
print(col)

[False False False  True False False False False  True False False False
  True False False]
3
[ 12279. -26024.  28745.      0.  31244.  -2365.  -6974.  -9212.      0.
 -17722.  16132.  25933.      0. -16431.  29810.]
[ 12279 -26024  28745      0  31244  -2365  -6974  -9212      0 -17722
  16132  25933      0 -16431  29810]
[-26024. -17722. -16431.  -9212.  -6974.  -2365.      0.      0.      0.
  12279.  16132.  25933.  28745.  29810.  31244.]
[[-26024.  -2365.  16132.]
 [-17722.      0.  25933.]
 [-16431.      0.  28745.]
 [ -9212.      0.  29810.]
 [ -6974.  12279.  31244.]]
[-2365.     0.     0.     0. 12279.]
