In [2]:
import numpy as np
np.random.rand()
# 0.06600758835806675

0.5474785610872177

In [ ]:
np.random.rand() * 100
# 69.76076924077643

In [ ]:
np.random.rand(5)
# array([0.83745099, 0.58426808, 0.89206204, 0.41149807, 0.42445145])

In [ ]:
np.random.rand(2, 3)
# array([[0.94931212, 0.06680018, 0.26707599],
#      [0.67908873, 0.18001743, 0.97732239]])

In [3]:
np.random.rand(2, 3, 4, 10, 12, 23)

array([[[[[[6.56071387e-03, 3.66961508e-01, 3.24883870e-01, ...,
            1.80492835e-01, 9.13778171e-02, 9.55371504e-01],
           [9.03573473e-01, 4.05647374e-01, 8.85614401e-01, ...,
            4.97902748e-01, 6.09776499e-01, 5.39857996e-01],
           [1.47372663e-01, 3.62646872e-01, 2.90632946e-01, ...,
            8.37268620e-01, 8.29830817e-01, 3.21256493e-01],
           ...,
           [9.38570667e-01, 1.91752780e-01, 1.79322102e-01, ...,
            3.07171233e-02, 8.89673934e-01, 5.32904837e-01],
           [4.08269730e-01, 3.90680214e-01, 6.26585974e-01, ...,
            2.03316347e-01, 3.74485062e-02, 8.34655324e-01],
           [6.44207272e-01, 4.98902602e-01, 2.57434481e-01, ...,
            6.11286419e-01, 2.86104629e-01, 1.98606102e-01]],

          [[6.64643151e-01, 7.52407466e-01, 2.63512692e-01, ...,
            2.79404801e-01, 4.14118762e-01, 5.82993986e-01],
           [9.52820250e-01, 4.60969362e-01, 6.81352322e-01, ...,
            2.54700796e-02, 1.58148

In [6]:
shape = (3, 4)
np.random.rand(shape)
# TypeError: 'tuple' object cannot be interpreted as an integer
# Ошибка типов: кортеж не может быть интерпретирован как целое число.

TypeError: 'tuple' object cannot be interpreted as an integer

In [5]:
shape = (3, 4)
np.random.rand(*shape)
# array([[0.66169176, 0.19455777, 0.06451088, 0.31919608],
#        [0.73536951, 0.67104408, 0.4762727 , 0.88153576],
#        [0.70672971, 0.96677145, 0.09273995, 0.86356465]])

array([[0.54137162, 0.24490253, 0.73980038, 0.69244771],
       [0.16596242, 0.18628391, 0.46939433, 0.12223156],
       [0.59405448, 0.11319745, 0.07765308, 0.85977305]])

In [4]:
shape = (2, 3)
np.random.sample(shape)
# array([[0.39756103, 0.01995168, 0.2768951 ],
#       [0.82195372, 0.26435273, 0.00957881]])

array([[0.66881931, 0.50788478, 0.98796781],
       [0.03348137, 0.76414158, 0.11075474]])

In [7]:
uniform(low=0.0, high=1.0, size=None)

NameError: name 'uniform' is not defined

In [8]:
np.random.uniform()
# 0.951557685543591

0.207115801827769

In [ ]:
np.random.uniform(-30, 50)
# 38.47365525953661

In [ ]:
np.random.uniform(0.5, 0.75, size=5)
# array([0.58078945, 0.58860342, 0.73790553, 0.63448265, 0.70920297])

In [ ]:
np.random.uniform(-1000, 500, size=(2, 3))
# array([[ 129.22164163,   77.69090611, -132.9656972 ],
#        [  18.65802226, -317.14793906,   85.3613547 ]])

In [ ]:
randint(low, high=None, size=None, dtype=int)

In [ ]:
np.random.randint(4, size=(2,3))
# array([[3, 0, 1],
#       [2, 1, 3]])

In [ ]:
np.random.randint(6, 12, size=(3,3))
# array([[ 9,  6, 10],
#        [10, 11, 10],
#        [ 7, 10, 11]])

ГЕНЕРАЦИЯ ВЫБОРОК

In [ ]:
arr = np.arange(6)
print(arr)
# [0 1 2 3 4 5]
print(np.random.shuffle(arr))
# None
arr
# array([0, 5, 1, 3, 2, 4])

In [9]:
playlist = ["The Beatles", "Pink Floyd", "ACDC", "Deep Purple"]
shuffled = np.random.permutation(playlist)
print(shuffled)
# ['The Beatles' 'Pink Floyd' 'Deep Purple' 'ACDC']
print(playlist)
# ['The Beatles', 'Pink Floyd', 'ACDC', 'Deep Purple']

['ACDC' 'The Beatles' 'Pink Floyd' 'Deep Purple']
['The Beatles', 'Pink Floyd', 'ACDC', 'Deep Purple']


In [ ]:
np.random.permutation(10)
# array([7, 8, 2, 9, 4, 3, 1, 0, 5, 6])

In [ ]:
choice(a, size=None, replace=True)

In [ ]:
workers = ['Ivan', 'Nikita', 'Maria', 'John', 'Kate']
 
choice = np.random.choice(workers, size=2, replace=False)
print(choice)

In [10]:
workers = ['Ivan', 'Nikita', 'Maria', 'John', 'Kate']
choice = np.random.choice(workers, size=10, replace=False)
print(choice)
# ValueError: Cannot take a larger sample than population when 'replace=False'
# Ошибка значения: нельзя получить выборку больше, чем популяция (популяция — весь доступный набор объектов, из которого получаем выборку), если replace=False (то есть выборка без повторений).

ValueError: Cannot take a larger sample than population when 'replace=False'

In [ ]:
choice = np.random.choice([1,2,3,4,5,6], size=10)
print(choice)
# [3 5 5 6 6 4 2 2 1 3]

SEED ГЕНЕРАТОРА ПСЕВДОСЛУЧАЙНЫХ ЧИСЕЛ

In [15]:
np.random.seed(23)
np.random.randint(10, size=(3,4))
# array([[3, 6, 8, 9],
#        [6, 8, 7, 9],
#        [3, 6, 1, 2]])

array([[3, 6, 8, 9],
       [6, 8, 7, 9],
       [3, 6, 1, 2]])

In [14]:
np.random.seed(100)
print(np.random.randint(10, size=3))
# [8 8 3]
print(np.random.randint(10, size=3))
# [7 7 0]
print(np.random.randint(10, size=3))
# [4 2 5]

[8 8 3]
[7 7 0]
[4 2 5]
