In [1]:
import numpy as np
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
vec1 + vec2
# array([14. , 10. , 10.6, 15.5])

array([14. , 10. , 10.6, 15.5])

In [2]:
list1 = [2, 4, 7, 2.5]
list2 = [12, 6, 3.6, 13]
list1 + list2
# [2, 4, 7, 2.5, 12, 6, 3.6, 13]

[2, 4, 7, 2.5, 12, 6, 3.6, 13]

In [3]:
[x + y for x, y in zip(list1, list2)]
# [14, 10, 10.6, 15.5]

[14, 10, 10.6, 15.5]

In [4]:
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
vec1 * vec2
# array([24. , 24. , 25.2, 32.5])

array([24. , 24. , 25.2, 32.5])

In [5]:
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6])
 
vec1 * vec2
# ValueError: operands could not be broadcast together with shapes (4,) (3,)
# Ошибка значения: операнд не может быть распространён одновременно на структуры с формами (4,) и (3,).

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

Исключением является случай, когда операция происходит с вектором и одним числом. Например, вектор целиком можно умножить на число или возвести в степень этого числа:

In [6]:
vec = np.arange(5)
vec * 10
# array([ 0, 10, 20, 30, 40])
vec ** 2
# array([ 0,  1,  4,  9, 16])

array([ 0,  1,  4,  9, 16])

In [7]:
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
 
vec1 > vec2
# array([False, False,  True, False])

array([False, False,  True, False])

In [8]:
vec = np.array([14,15,9,26,53,5,89])
vec <= 26
# array([ True,  True,  True,  True, False,  True, False])

array([ True,  True,  True,  True, False,  True, False])

Длина вектора, то есть расстояние между его началом и концом, [в евклидовом пространстве] вычисляется как квадратный корень из суммы квадратов всех его координат

In [10]:
vec = np.array([3, 4])

In [11]:
length = np.sqrt(np.sum(vec ** 2))
print(length)
# 5.0

5.0


In [12]:
length = np.linalg.norm(vec)
print(length)
# 5.0

5.0


Расстояние между двумя векторами, то есть расстояние между их концами, [в евклидовом пространстве] вычисляется как квадратный корень из суммы квадратов разностей соответствующих координат

In [13]:
vec1 = np.array([0, 3, 5])
vec2 = np.array([12, 4, 7])
distance = np.sqrt(np.sum((vec1 - vec2) ** 2))
distance
# 12.206555615733702

12.206555615733702

In [14]:
vec1 = np.array([0, 3, 5])
vec2 = np.array([12, 4, 7])
distance = np.linalg.norm(vec1 - vec2)
distance
# 12.206555615733702

12.206555615733702

скалярным произведением двух векторов называют сумму произведений их соответствующих координат

In [15]:
vec1 = np.arange(1, 6)
vec2 = np.linspace(10, 20, 5)
scalar_product = np.sum(vec1 * vec2)
scalar_product
# 250.0

250.0

In [16]:
scalar_product = np.dot(vec1, vec2)
scalar_product
# 250.0

250.0

равенство скалярного произведения нулю означает перпендикулярность рассматриваемых векторов

In [17]:
x = np.array([25, 0])
y = np.array([0, 10])
np.dot(x, y)
# 0

0

БАЗОВЫЕ СТАТИСТИЧЕСКИЕ ФУНКЦИИ ДЛЯ ВЕКТОРОВ

In [19]:
vec = np.array([2,7,18,28,18,1,8,4])
vec.min()
# 1
np.max(vec)
# 28

28

In [20]:
vec.mean()
# 10.75

10.75